version: '3.8'

services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - $GRAFANA_DATA:/var/lib/grafana
      - $GRAFANA_CONFIG:/etc/grafana/grafana.ini
    ports:
      - '3000:3000'
    restart: unless-stopped
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:v2.29.1
    continer_name: prometheus
    volumes:
      - $PROMETHEUS_DATA:/prometheus
      - $PROMETHEUS_CONFIG:/etc/prometheus/prometheus.yml
    ports:
      - '9090:9090'
    restart: unless-stopped
    networks:
      - monitoring
      - prometheus

  snmp_exporter:
    image: prom/snmp-exporter:v0.18.0
    container_name: snmp_exporter
    volumes:
      - $SNMP_EXPORTER_DATA:/etc/snmp_exporter/snmp.yml
    restart: unless-stopped
    networks:
      - prometheus

  speedtest_ exporter:
    image: miguelndecarvalho/speedtest-exporter
    container_name: speedtest_exporter
    restart: unless-stopped
    networks:
      - prometheus

networks:
  monitoring:
  prometheus:
    internal: true


