version: 3.8

services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    environment:
      PUID: $PUID
      PGID: $PGID
      PUDIR: $PUDIR
    volumes:
      - $PUDIR/homepage:/app/config
      - $PUDIR/public:/app/public 
    restart: unless-stopped
    depends_on:
      - dockerproxy
    networks:
      - homepage
      - proxydocker

    dockerproxy:
      image: ghcr.io/tecnativa/docker-socket-proxy:latest
      container_name: dockerproxy
      environment:
        CONTAINERS: 1
        SERVICES: 1
        TASKS: 1
        POST: 0
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro
      restart: unless-stopped
      networks:
        - proxydocker

networks:
  homepage:
  proxydocker:
    internal: true
