version: 3.8

services:
  nginx:
    image: nginx
    ports:
      - 80
      - 443
    volumes:
      - /etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/ssl:/etc/nginx/ssl:ro
    restart: unless-stopped
    networks:
      - nginx-proxy

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    environment:
      PUID: $PUID
      PGID: $PGID
      PUDIR: $PUDIR
    volumes:
      - $PUDIR/homepage:/app/config
      - $PUDIR/public:/app/public 
    restart: unless-stopped
    depends_on:
      - dockerproxy
    networks:
      - nginx-proxy
      - docker-proxy

    dockerproxy:
      image: ghcr.io/tecnativa/docker-socket-proxy:latest
      container_name: docker-proxy
      environment:
        CONTAINERS: 1
        SERVICES: 1
        TASKS: 1
        POST: 0
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro
      restart: unless-stopped
      networks:
        - docker-proxy

networks:
  nginx-proxy:
  docker-proxy:
    internal: true
