version: '3.8'

services:
  pihole:
    container_name: pihole-dns
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
    environment:
      TZ: America/NewYork
      WEBPASSWORD: $PIHOLE_PASSWORD
    volumes:
      - $PIHOLE_DATA:/etc/pihole
      - $PIHOLE_DNS:/etc/dnsmasq.d
    restart: unless-stopped
