global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'snmp_exporter'
    static_configs:
      - targets: ['<TARGET-IP-HERE>']
    metrics_path: /snmp
    params:
      module: [default]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: snmp_exporter:9116

  - job_name: 'speedtest_exporter'
    scrape_interval: 1h
    scrpape_timeout: 1m
    static_configs:
      - targets: ['speedtest_exporter:9798']

