---

- hosts: piholehosts
  become: yes
  tasks:
    - name: Ensure Pi Hole Group exists
      ansible.builtin.group:
        name: piholegroup
        system: yes

    - name: Create Pi Hole User
      ansible.builtin.user:
        name: pihole
        comment: "Pi-hole service user"
        group: piholegroup
        system: yes
        shell: /usr/bin/nologin
        create_home: no

    - name: Pull and run pihole from docker
      community.docker.docker_container:
          name: pihole
          image: pihole/pihole:latest
          ports:
            - "53:53/tcp"
            - "53:53/udp"
            - "67:67/udp"
            - "80:80/tcp"
            - "443:443/tcp"
          volumes:
            - "/etc/pihole/:/etc/pihole/"
            - "/etc/dnsmasq.d/:/etc/dnsmasq.d/"
          environment:
            TZ: "America/New_York"
            WEBPASSWORD: "{{ pihole_password }}"
          restart_policy: always
          state: started
          user: "pihole"

