---

- hosts: webservers
  become: yes

  tasks:
    - name: Install NGINX
      ansible.builtin.apt:
        name: nginx
        state: present

    - name: Transfer NGINX configuration template
      ansible.builtin.template:
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify: restart nginx

    - name: Ensure NGINX is running and enabled
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes

  handlers:
    - name: restart nginx
      ansible.builtin.service:
        name: nginx
        state: restarted